### ISSUE TITLE
Не отображаются фотографии в Сафари

### ISSUE THREAD

**Issue by denisfl** [denisfl/137781-keksogram#1]
@o0 я тут заметил, что шаблонизация через `template` не работает в Safari (и на мобильных устройствах)

![image](https://cloud.githubusercontent.com/assets/1903344/11561847/265d4d46-99db-11e5-83ed-a20aaf7c303e.png)

**Comment by o0** [comment]
Вижу-вижу, проверил у себя в Safari, все работает, поддержка template у Safari с версии 7.1. Методом пристального взгляда отлаживать не советую, советую включить дебаггер на этой строчке и посмотреть чему равны все переменные. `template`, `template.content` и так далее.

**Comment by denisfl** [comment]
На http://o0.github.io/keksobooking/ ошибка такая же. Проверка показывает children[0] - undefined
Safari 8.0.7

**Comment by o0** [comment]
Ок, проверю.
